import {
  User,
  StudentProfile,
  PlacementDrive,
  DriveApplication,
  InterviewSchedule,
  InternshipOpportunity,
  AlumniReferral,
  MockDrive,
  MockResult,
  InAppNotification,
  AuditLogEntry,
} from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "user-student-1",
    name: "Aarav Sharma",
    email: "aarav.sharma@university.edu.in",
    role: "STUDENT",
    department: "Computer Science & Engineering",
  },
  {
    id: "user-admin-1",
    name: "Dr. Rajesh K. Varma",
    email: "dean.placements@university.edu.in",
    role: "PLACEMENT_ADMIN",
    department: "Training & Placement Cell",
  },
  {
    id: "user-officer-1",
    name: "Prof. Sunita Deshmukh",
    email: "sunita.d@university.edu.in",
    role: "PLACEMENT_OFFICER",
    department: "Training & Placement Cell",
  },
  {
    id: "user-recruiter-1",
    name: "Vikram Malhotra",
    email: "v.malhotra@goldmansachs.com",
    role: "RECRUITER",
    department: "University Talent Acquisition",
  },
  {
    id: "user-alumni-1",
    name: "Pooja Hegde",
    email: "pooja.hegde@alumni.university.edu",
    role: "ALUMNI",
    department: "Class of 2022 - Microsoft",
  },
  {
    id: "user-coordinator-1",
    name: "Prof. Arvind Raman",
    email: "arvind.raman@university.edu.in",
    role: "INTERNSHIP_COORDINATOR",
    department: "Department of Industry Relations",
  },
];

export const MOCK_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: "student-1",
    userId: "user-student-1",
    fullName: "Aarav Sharma",
    universityId: "2022BCS0142",
    email: "aarav.sharma@university.edu.in",
    phone: "+91 98765 43210",
    branch: "Computer Science & Engineering",
    degree: "B.Tech",
    graduationYear: 2026,
    cgpa: 8.65,
    tenthPercentage: 92.4,
    twelfthPercentage: 89.2,
    activeBacklogs: 0,
    historyOfBacklogs: 0,
    skills: ["Java", "Python", "Data Structures", "Algorithms", "React", "Next.js", "PostgreSQL", "System Design", "Git"],
    projects: [
      {
        title: "Distributed Fault-Tolerant Cache",
        description: "Implemented a Raft consensus distributed key-value cache handling 25,000 QPS with automated leader election.",
        technologies: ["Go", "gRPC", "Docker"],
        link: "https://github.com/aarav/dist-cache",
      },
      {
        title: "Campus Resource Allocation Platform",
        description: "Engineered real-time room and lab scheduling portal serving 4,500 students with optimistic concurrency locking.",
        technologies: ["Next.js", "PostgreSQL", "Tailwind CSS"],
        link: "https://github.com/aarav/campus-portal",
      },
    ],
    certifications: [
      { name: "AWS Certified Solutions Architect - Associate", issuer: "Amazon Web Services", year: 2024 },
      { name: "Certified Kubernetes Application Developer", issuer: "Linux Foundation", year: 2025 },
    ],
    internships: [
      {
        company: "InnoTech Labs",
        role: "Software Engineering Intern",
        duration: "May 2025 - Jul 2025",
        description: "Optimized indexing algorithms on Apache Cassandra, dropping query p99 latency by 32%.",
      },
    ],
    resumeUrl: "/resumes/aarav_sharma_resume.pdf",
    githubUrl: "https://github.com/aarav-sharma-tech",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma-cs",
    portfolioUrl: "https://aaravsharma.dev",
    bio: "Pre-final year Computer Science undergraduate focused on distributed systems, database internals, and scalable cloud applications.",
    profileCompletionPercentage: 95,
    placementStatus: "Not Placed",
  },
  {
    id: "student-2",
    userId: "user-student-2",
    fullName: "Rohan Nambiar",
    universityId: "2022BIT0089",
    email: "rohan.n@university.edu.in",
    phone: "+91 98450 11223",
    branch: "Information Technology",
    degree: "B.Tech",
    graduationYear: 2026,
    cgpa: 7.42,
    tenthPercentage: 84.0,
    twelfthPercentage: 81.5,
    activeBacklogs: 1,
    historyOfBacklogs: 2,
    skills: ["Python", "FastAPI", "SQL", "JavaScript", "Docker", "Machine Learning"],
    projects: [
      {
        title: "Medical Image Segmentation",
        description: "Trained U-Net model on CT scan segmentations with 91.2% Dice coefficient.",
        technologies: ["PyTorch", "OpenCV", "Python"],
      },
    ],
    certifications: [
      { name: "Deep Learning Specialization", issuer: "Coursera / DeepLearning.AI", year: 2024 },
    ],
    internships: [],
    resumeUrl: "/resumes/rohan_nambiar.pdf",
    githubUrl: "https://github.com/rohannambiar",
    linkedinUrl: "https://linkedin.com/in/rohan-nambiar",
    bio: "Passionate about applied machine learning and backend API services.",
    profileCompletionPercentage: 80,
    placementStatus: "Not Placed",
  },
  {
    id: "student-3",
    userId: "user-student-3",
    fullName: "Priya Sundaram",
    universityId: "2022ECE0051",
    email: "priya.s@university.edu.in",
    phone: "+91 97654 32190",
    branch: "Electronics & Communication Engineering",
    degree: "B.Tech",
    graduationYear: 2026,
    cgpa: 9.15,
    tenthPercentage: 95.0,
    twelfthPercentage: 93.6,
    activeBacklogs: 0,
    historyOfBacklogs: 0,
    skills: ["C++", "Embedded C", "VHDL/Verilog", "Python", "RTOS", "Computer Architecture"],
    projects: [
      {
        title: "RISC-V 5-Stage Pipelined Processor",
        description: "Synthesized a 32-bit RV32I pipelined core with branch prediction on Xilinx Artix-7 FPGA.",
        technologies: ["Verilog", "ModelSim", "FPGA"],
      },
    ],
    certifications: [
      { name: "VLSI Digital Design & Verification", issuer: "Cadence", year: 2024 },
    ],
    internships: [
      {
        company: "Texas Instruments",
        role: "Silicon Engineering Intern",
        duration: "May 2025 - Jul 2025",
        description: "Formulated UVM testbench suites for high-speed SPI controller blocks.",
      },
    ],
    resumeUrl: "/resumes/priya_sundaram.pdf",
    githubUrl: "https://github.com/priyasundaram",
    linkedinUrl: "https://linkedin.com/in/priya-sundaram",
    bio: "Aspiring hardware & silicon systems engineer with strong grasp of digital VLSI and microarchitecture.",
    profileCompletionPercentage: 90,
    placementStatus: "Not Placed",
  },
];

export const MOCK_PLACEMENT_DRIVES: PlacementDrive[] = [
  {
    id: "drive-1",
    companyName: "Goldman Sachs",
    companyLogo: "GS",
    companyTier: "Tier 1 (Dream)",
    jobTitle: "Software Development Engineer (Campus Analyst)",
    jobDescription: `About Goldman Sachs Engineering:
Goldman Sachs Engineers are innovators and problem-solvers who design and implement scalable, resilient systems that drive global financial markets. As a Campus Analyst, you will be embedded in dynamic agile teams building low-latency trading engines, risk calculation grids, automated regulatory analytics, or secure cloud infrastructure.

Key Responsibilities:
- Design, build, test, and release robust, high-availability software services using Java, C++, Python, or TypeScript.
- Analyze algorithmic time-complexity, identify computational bottlenecks, and architect distributed memory-cache systems.
- Partner with quantitative strategists, portfolio managers, and infrastructure architects to translate sophisticated financial models into production-ready software.
- Enforce strict engineering standards including test-driven development, continuous integration, and secure code audits.

Eligibility & Requirements:
- Candidates graduating in 2026 with B.Tech/M.Tech in Computer Science, Information Technology, or Electronics.
- Minimum 7.50 CGPA with no active backlogs.
- Strong foundational grasp of Data Structures, Algorithms, Object-Oriented Design, and Multi-threading.`,
    jobLocation: "Bengaluru / Hyderabad",
    employmentType: "Full-Time",
    ctcLpa: 24.5,
    stipendMonthly: 85000,
    applicationDeadline: "2026-10-18T23:59:59Z",
    driveDate: "2026-10-24T09:00:00Z",
    selectionRounds: [
      "Online Assessment (Aptitude & DSA)",
      "Technical Round 1 (Algorithms & Systems)",
      "Technical Round 2 (Design & Projects)",
      "Leadership & Cultural Fitment (HR)",
    ],
    eligibleBranches: [
      "Computer Science & Engineering",
      "Information Technology",
      "Electronics & Communication Engineering",
    ],
    minCgpa: 7.5,
    maxBacklogs: 0,
    minTenthPercentage: 70.0,
    minTwelfthPercentage: 70.0,
    allowedGraduationYears: [2026],
    requiredSkills: ["Data Structures", "Algorithms", "Java", "C++", "System Design", "SQL"],
    otherConditions: "Immediate joining for summer internship preceding full-time onboarding.",
    status: "Applications Open",
    totalApplicants: 142,
    shortlistedCount: 38,
    selectedCount: 8,
    createdBy: "user-admin-1",
    createdAt: "2026-09-25T10:00:00Z",
    updatedAt: "2026-10-01T15:30:00Z",
  },
  {
    id: "drive-2",
    companyName: "Microsoft Corporation",
    companyLogo: "MS",
    companyTier: "Tier 1 (Dream)",
    jobTitle: "Software Engineer - Azure Core & Distributed Platforms",
    jobDescription: `Microsoft Azure is the world's cloud platform. We are seeking talented, curious, and collaborative undergraduate engineers to work on our hyperscale cloud fabric, hypervisor layers, container networking, and intelligent observability stacks.

Responsibilities:
- Build high-performance, fault-tolerant backend services handling billions of transactions daily.
- Participate in design reviews, architectural discussions, and root cause analysis of distributed edge failures.
- Implement automated testing frameworks and reliability metrics to safeguard cloud SLAs.

Eligibility Criteria:
- 2026 graduating B.Tech students in CSE, IT, ECE, or EE.
- Minimum CGPA of 8.00 with 0 active backlogs.
- 10th and 12th minimum 75%.`,
    jobLocation: "Hyderabad / Noida / Bengaluru",
    employmentType: "FTE + Internship",
    ctcLpa: 28.0,
    stipendMonthly: 100000,
    applicationDeadline: "2026-10-22T18:00:00Z",
    driveDate: "2026-10-28T09:30:00Z",
    selectionRounds: [
      "Codility Online Coding Round (3 Questions)",
      "Technical Interview 1 (Trees & Graphs)",
      "Technical Interview 2 (Distributed Systems)",
      "AA (As Appropriate) Director Round",
    ],
    eligibleBranches: [
      "Computer Science & Engineering",
      "Information Technology",
    ],
    minCgpa: 8.0,
    maxBacklogs: 0,
    minTenthPercentage: 75.0,
    minTwelfthPercentage: 75.0,
    allowedGraduationYears: [2026],
    requiredSkills: ["Algorithms", "Data Structures", "C++", "Java", "Operating Systems", "Networking"],
    otherConditions: "Must have strong understanding of memory management and concurrency primitives.",
    status: "Applications Open",
    totalApplicants: 189,
    shortlistedCount: 42,
    selectedCount: 12,
    createdBy: "user-admin-1",
    createdAt: "2026-09-28T08:00:00Z",
    updatedAt: "2026-10-02T12:00:00Z",
  },
  {
    id: "drive-3",
    companyName: "Texas Instruments",
    companyLogo: "TI",
    companyTier: "Tier 1 (Dream)",
    jobTitle: "Embedded Software & Silicon Applications Engineer",
    jobDescription: `Texas Instruments is seeking passionate electronics and computer engineers to work on next-generation automotive radar, industrial IoT microcontrollers, and ultra-low-power DSP architectures.

Responsibilities:
- Write bare-metal C and RTOS firmware drivers for TI's Sitara and C2000 processor families.
- Perform board bring-up, oscilloscopes/logic analyzer verification, and hardware debugging.
- Optimize algorithmic execution on DSP core units.`,
    jobLocation: "Bengaluru",
    employmentType: "Full-Time",
    ctcLpa: 21.0,
    stipendMonthly: 75000,
    applicationDeadline: "2026-10-15T23:59:59Z",
    driveDate: "2026-10-20T10:00:00Z",
    selectionRounds: [
      "Written Assessment (Aptitude + Core Hardware & C)",
      "Technical Round 1 (Microcontrollers & C)",
      "Technical Round 2 (Analog & Digital Interfacing)",
      "HR & Fitment Interview",
    ],
    eligibleBranches: [
      "Electronics & Communication Engineering",
      "Electrical & Electronics Engineering",
    ],
    minCgpa: 7.0,
    maxBacklogs: 0,
    minTenthPercentage: 65.0,
    minTwelfthPercentage: 65.0,
    allowedGraduationYears: [2026],
    requiredSkills: ["C++", "Embedded C", "Microcontrollers", "RTOS", "Digital Electronics"],
    status: "Applications Open",
    totalApplicants: 64,
    shortlistedCount: 18,
    selectedCount: 5,
    createdBy: "user-officer-1",
    createdAt: "2026-09-20T11:00:00Z",
    updatedAt: "2026-09-30T16:00:00Z",
  },
  {
    id: "drive-4",
    companyName: "Oracle Cloud Infrastructure",
    companyLogo: "OCI",
    companyTier: "Tier 2 (Super Dream)",
    jobTitle: "Cloud Infrastructure Engineer",
    jobDescription: `OCI provides enterprise cloud compute, storage, and networking. Engineers will build control planes, telemetry pipelines, and fleet orchestrators using modern Java and Go.`,
    jobLocation: "Bengaluru / Hyderabad",
    employmentType: "Full-Time",
    ctcLpa: 17.5,
    stipendMonthly: 60000,
    applicationDeadline: "2026-10-30T23:59:59Z",
    driveDate: "2026-11-05T09:00:00Z",
    selectionRounds: [
      "Online Coding & System Fundamentals",
      "Technical Discussion 1",
      "Technical Discussion 2",
      "HR Interview",
    ],
    eligibleBranches: [
      "Computer Science & Engineering",
      "Information Technology",
      "Electronics & Communication Engineering",
    ],
    minCgpa: 7.0,
    maxBacklogs: 1,
    minTenthPercentage: 60.0,
    minTwelfthPercentage: 60.0,
    allowedGraduationYears: [2026],
    requiredSkills: ["Java", "SQL", "Linux", "Data Structures", "Docker"],
    status: "Applications Open",
    totalApplicants: 110,
    shortlistedCount: 25,
    selectedCount: 6,
    createdBy: "user-admin-1",
    createdAt: "2026-10-01T09:00:00Z",
    updatedAt: "2026-10-01T09:00:00Z",
  },
  {
    id: "drive-5",
    companyName: "Deloitte USI",
    companyLogo: "DEL",
    companyTier: "Tier 3 (Core/Mass)",
    jobTitle: "Associate Analyst - Advisory & Technology",
    jobDescription: `Deloitte Consulting and Advisory delivers digital transformation across Enterprise Applications, Cloud, Cyber Risk, and AI automation for Fortune 500 institutions globally.`,
    jobLocation: "Hyderabad / Mumbai / Gurugram",
    employmentType: "Full-Time",
    ctcLpa: 9.2,
    applicationDeadline: "2026-11-10T23:59:59Z",
    driveDate: "2026-11-18T09:00:00Z",
    selectionRounds: [
      "Aptitude, Verbal & Coding Assessment (AMCAT)",
      "Technical & Case Study Interview",
      "Partner & HR Discussion",
    ],
    eligibleBranches: ["All Engineering Branches"],
    minCgpa: 6.5,
    maxBacklogs: 1,
    minTenthPercentage: 60.0,
    minTwelfthPercentage: 60.0,
    allowedGraduationYears: [2026],
    requiredSkills: ["Problem Solving", "SQL", "Python", "Communication", "Analytical Aptitude"],
    status: "Applications Open",
    totalApplicants: 320,
    shortlistedCount: 95,
    selectedCount: 40,
    createdBy: "user-officer-1",
    createdAt: "2026-10-02T14:00:00Z",
    updatedAt: "2026-10-02T14:00:00Z",
  },
];

export const MOCK_APPLICATIONS: DriveApplication[] = [
  {
    id: "app-1",
    driveId: "drive-1",
    studentId: "student-1",
    status: "Technical Interview",
    currentRound: "Technical Round 2 (Design & Projects)",
    appliedAt: "2026-09-26T14:20:00Z",
    updatedAt: "2026-10-02T11:15:00Z",
    resumeUrl: "/resumes/aarav_sharma_resume.pdf",
    feedback: "Exceptional command of concurrency and indexing. Cleared Round 1 with high score.",
    history: [
      {
        status: "Applied",
        roundName: "Application Submission",
        timestamp: "2026-09-26T14:20:00Z",
        updatedBy: "Student",
        remarks: "Application verified against academic database.",
      },
      {
        status: "Under Review",
        roundName: "Resume Screening",
        timestamp: "2026-09-27T10:00:00Z",
        updatedBy: "Prof. Sunita Deshmukh",
        remarks: "Profile matched criteria: 8.65 CGPA, 0 backlogs.",
      },
      {
        status: "Shortlisted",
        roundName: "Shortlist for Assessment",
        timestamp: "2026-09-28T16:45:00Z",
        updatedBy: "Dr. Rajesh K. Varma",
        remarks: "Eligible for HackerRank assessment link.",
      },
      {
        status: "Assessment",
        roundName: "Online Assessment (Aptitude & DSA)",
        timestamp: "2026-09-29T18:00:00Z",
        updatedBy: "Vikram Malhotra",
        remarks: "Score: 94/100. Solved all 3 algorithmic challenges within 48 mins.",
      },
      {
        status: "Technical Interview",
        roundName: "Technical Round 1 (Algorithms & Systems)",
        timestamp: "2026-10-02T11:15:00Z",
        updatedBy: "Vikram Malhotra",
        remarks: "Recommended for Round 2. Deep insight into Raft consensus.",
      },
    ],
  },
  {
    id: "app-2",
    driveId: "drive-2",
    studentId: "student-1",
    status: "Shortlisted",
    currentRound: "Codility Online Coding Round",
    appliedAt: "2026-09-29T09:10:00Z",
    updatedAt: "2026-09-30T12:00:00Z",
    resumeUrl: "/resumes/aarav_sharma_resume.pdf",
    history: [
      {
        status: "Applied",
        roundName: "Application Submission",
        timestamp: "2026-09-29T09:10:00Z",
        updatedBy: "Student",
      },
      {
        status: "Shortlisted",
        roundName: "Eligibility Verification",
        timestamp: "2026-09-30T12:00:00Z",
        updatedBy: "Prof. Sunita Deshmukh",
        remarks: "Meets Tier 1 minimum CGPA 8.00 criteria.",
      },
    ],
  },
];

export const MOCK_INTERVIEWS: InterviewSchedule[] = [
  {
    id: "int-1",
    applicationId: "app-1",
    driveId: "drive-1",
    studentId: "student-1",
    studentName: "Aarav Sharma",
    companyName: "Goldman Sachs",
    jobTitle: "Software Development Engineer (Campus Analyst)",
    roundName: "Technical Round 2 (Design & Projects)",
    scheduledAt: "2026-10-08T14:30:00Z",
    mode: "Virtual",
    locationOrLink: "https://goldmansachs.zoom.us/j/84920491823",
    interviewerName: "Siddharth Rao (VP, Core Engineering)",
    status: "Scheduled",
  },
  {
    id: "int-2",
    applicationId: "app-3",
    driveId: "drive-3",
    studentId: "student-3",
    studentName: "Priya Sundaram",
    companyName: "Texas Instruments",
    jobTitle: "Embedded Software & Silicon Applications Engineer",
    roundName: "Technical Round 1 (Microcontrollers & C)",
    scheduledAt: "2026-10-10T11:00:00Z",
    mode: "In-Person (Campus)",
    locationOrLink: "Placement Cell Block B, Interview Room 04",
    interviewerName: "Ananya Deshpande (Lead Architect, TI India)",
    status: "Scheduled",
  },
];

export const MOCK_INTERNSHIPS: InternshipOpportunity[] = [
  {
    id: "intern-1",
    companyName: "Cisco Systems",
    companyLogo: "CSCO",
    roleTitle: "Cloud Security & SD-WAN Engineering Intern",
    duration: "6 Months (Jan 2026 - Jun 2026)",
    stipendMonthly: 65000,
    location: "Bengaluru, India",
    type: "Hybrid",
    requiredSkills: ["Python", "TCP/IP", "Linux", "Docker", "Cybersecurity Basics"],
    eligibilitySummary: "B.Tech CSE/IT/ECE, Min CGPA 7.50, No active backlogs",
    applicationDeadline: "2026-10-25T23:59:59Z",
    description: "Work with Cisco Talos and Umbrella threat intelligence teams to construct automated security telemetry scanners.",
    openings: 8,
    status: "Open",
    appliedCount: 68,
    createdAt: "2026-09-28T10:00:00Z",
  },
  {
    id: "intern-2",
    companyName: "Morgan Stanley",
    companyLogo: "MS",
    roleTitle: "Quantitative Technology & Data Engineering Intern",
    duration: "Summer 2026 (10 Weeks)",
    stipendMonthly: 90000,
    location: "Mumbai, India",
    type: "On-site",
    requiredSkills: ["Python", "C++", "Statistics", "SQL", "Pandas"],
    eligibilitySummary: "All branches with strong mathematical & coding aptitude, Min CGPA 8.00",
    applicationDeadline: "2026-10-30T23:59:59Z",
    description: "Design automated backtesting infrastructure and low-latency market feeds for institutional equities.",
    openings: 5,
    status: "Open",
    appliedCount: 94,
    createdAt: "2026-09-30T14:00:00Z",
  },
  {
    id: "intern-3",
    companyName: "Siemens Healthineers",
    companyLogo: "SH",
    roleTitle: "Medical Software & Image Processing Intern",
    duration: "6 Months",
    stipendMonthly: 45000,
    location: "Bengaluru, India",
    type: "On-site",
    requiredSkills: ["C++", "Computer Vision", "Python", "DICOM Standards"],
    eligibilitySummary: "CSE, ECE, Biomedical Engineering with CGPA ≥ 7.00",
    applicationDeadline: "2026-11-05T23:59:59Z",
    description: "Assist research scientists in MRI and CT artifact reduction algorithms using Deep Neural Networks.",
    openings: 4,
    status: "Open",
    appliedCount: 35,
    createdAt: "2026-10-01T12:00:00Z",
  },
];

export const MOCK_ALUMNI_REFERRALS: AlumniReferral[] = [
  {
    id: "alumni-ref-1",
    alumniName: "Pooja Hegde",
    alumniBatch: "Class of 2022 (B.Tech CSE)",
    alumniCurrentRole: "Software Engineer II at Microsoft",
    companyName: "Microsoft",
    companyLogo: "MS",
    roleTitle: "Software Engineer (New Grad - Distributed Systems)",
    location: "Bengaluru / Hyderabad",
    jobType: "Full-Time",
    experienceRequired: "2026 Batch Graduates",
    skills: ["C#", "C++", "Java", "Azure", "Distributed Systems", "Algorithms"],
    referralDeadline: "2026-10-25T23:59:59Z",
    referralInstructions: "Submit your updated 1-page PDF resume with GitHub link. Please highlight coursework in Operating Systems and Distributed Systems. I will review and refer through Microsoft internal portal.",
    contactEmail: "pooja.hegde@alumni.university.edu",
    openings: 3,
    status: "Active",
    createdAt: "2026-09-27T16:00:00Z",
  },
  {
    id: "alumni-ref-2",
    alumniName: "Nikhil Chawla",
    alumniBatch: "Class of 2021 (B.Tech IT)",
    alumniCurrentRole: "Senior Backend Engineer at Stripe",
    companyName: "Stripe",
    companyLogo: "ST",
    roleTitle: "Software Engineer - Financial Infrastructure",
    location: "Bengaluru / Remote",
    jobType: "Full-Time",
    experienceRequired: "2026 Graduates or 0-1 year experience",
    skills: ["Ruby", "Go", "Java", "PostgreSQL", "API Design", "Distributed Systems"],
    referralDeadline: "2026-11-01T23:59:59Z",
    referralInstructions: "Ensure you have at least one significant non-trivial backend project on your resume with clear API contracts and unit tests. Will provide internal referral directly to hiring manager.",
    contactEmail: "n.chawla@alumni.university.edu",
    openings: 2,
    status: "Active",
    createdAt: "2026-10-01T09:30:00Z",
  },
  {
    id: "alumni-ref-3",
    alumniName: "Dr. Sneha Pillai",
    alumniBatch: "Class of 2019 (B.Tech ECE)",
    alumniCurrentRole: "Silicon Architecture Lead at NVIDIA",
    companyName: "NVIDIA",
    companyLogo: "NV",
    roleTitle: "GPU ASIC Verification & Architecture Engineer",
    location: "Pune / Bengaluru",
    jobType: "Full-Time",
    experienceRequired: "2026 Batch B.Tech/M.Tech",
    skills: ["SystemVerilog", "UVM", "C++", "Computer Architecture", "Python"],
    referralDeadline: "2026-10-20T23:59:59Z",
    referralInstructions: "Looking for top performers in VLSI, Processor Design, or Computer Architecture. Attach transcript alongside resume.",
    contactEmail: "sneha.pillai@alumni.university.edu",
    openings: 4,
    status: "Active",
    createdAt: "2026-09-24T18:00:00Z",
  },
];

export const MOCK_MOCK_DRIVES: MockDrive[] = [
  {
    id: "mock-1",
    title: "National Campus Placement Simulation 2026",
    description: "Standardized institutional mock recruitment drive mirroring Tier-1 investment bank and product enterprise test patterns.",
    rounds: ["General & Quantitative Aptitude (30m)", "Data Structures & Algorithmic Coding (45m)", "Core Technical & OOPs QA (15m)"],
    durationMinutes: 90,
    totalMarks: 100,
    scheduledAt: "2026-10-12T10:00:00Z",
    status: "Active",
    registeredCount: 420,
    completedCount: 295,
  },
  {
    id: "mock-2",
    title: "Core Electronics & Embedded Systems Mock Drive",
    description: "Dedicated simulation for ECE/EE students covering digital electronics, C pointer mechanics, microcontrollers, and circuit analysis.",
    rounds: ["Hardware Fundamentals (40m)", "Firmware Coding in C (30m)", "Technical Viva (20m)"],
    durationMinutes: 90,
    totalMarks: 100,
    scheduledAt: "2026-10-16T14:00:00Z",
    status: "Upcoming",
    registeredCount: 165,
    completedCount: 0,
  },
];

export const MOCK_MOCK_RESULTS: MockResult[] = [
  {
    id: "res-1",
    mockDriveId: "mock-1",
    mockTitle: "National Campus Placement Simulation 2026",
    studentId: "student-1",
    studentName: "Aarav Sharma",
    aptitudeScore: 36, // out of 40
    codingScore: 38, // out of 40
    interviewScore: 18, // out of 20
    totalScore: 92,
    percentile: 97.4,
    strengths: [
      "Optimal algorithmic time complexity analysis on Dynamic Programming problems",
      "Fast mental math in Permutation & Combination quantitative sections",
      "Articulate explanation of database ACID guarantees during technical simulation",
    ],
    areasToImprove: [
      "Brush up on bit manipulation tricks for low-level interview edge questions",
      "Pace written explanations more evenly across multi-part questions",
    ],
    overallAssessment: "Strong readiness for Tier-1 Product Companies (CTC > 20 LPA). Excellent coding velocity and problem decomposition.",
    completedAt: "2026-10-02T16:30:00Z",
  },
];

export const MOCK_NOTIFICATIONS: InAppNotification[] = [
  {
    id: "notif-1",
    userId: "user-student-1",
    title: "Interview Scheduled: Goldman Sachs",
    message: "Technical Round 2 (Design & Projects) scheduled for Oct 08 at 02:30 PM. Check interview link in schedule.",
    type: "interview",
    link: "/dashboard/student/interviews",
    isRead: false,
    createdAt: "2026-10-02T11:20:00Z",
  },
  {
    id: "notif-2",
    userId: "user-student-1",
    title: "New Eligible Placement Drive",
    message: "Microsoft Corporation has published 'Software Engineer - Azure Core' (28.0 LPA). Your profile is ELIGIBLE.",
    type: "drive",
    link: "/dashboard/student/drives",
    isRead: false,
    createdAt: "2026-09-28T08:05:00Z",
  },
  {
    id: "notif-3",
    userId: "user-student-1",
    title: "Alumni Referral Available",
    message: "Pooja Hegde (Class of 2022) posted 3 referrals for Microsoft. Deadline: Oct 25.",
    type: "referral",
    link: "/dashboard/student/alumni-referrals",
    isRead: true,
    createdAt: "2026-09-27T16:15:00Z",
  },
  {
    id: "notif-4",
    userId: "user-student-1",
    title: "Application Status Updated",
    message: "Goldman Sachs: You have been progressed to 'Technical Interview' following assessment verification.",
    type: "application",
    link: "/dashboard/student/applications",
    isRead: true,
    createdAt: "2026-09-29T18:10:00Z",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "audit-1",
    actorName: "Dr. Rajesh K. Varma",
    actorRole: "PLACEMENT_ADMIN",
    action: "DRIVE_PUBLISHED",
    targetType: "Drive",
    targetId: "drive-2",
    targetTitle: "Microsoft Corporation - Azure Core",
    details: "Published placement drive with 28.0 LPA CTC, min CGPA 8.00, 2026 batch.",
    ipAddress: "192.168.1.104",
    timestamp: "2026-09-28T08:00:00Z",
  },
  {
    id: "audit-2",
    actorName: "Prof. Sunita Deshmukh",
    actorRole: "PLACEMENT_OFFICER",
    action: "STATUS_UPDATED",
    targetType: "Application",
    targetId: "app-1",
    targetTitle: "Aarav Sharma (Goldman Sachs)",
    details: "Advanced candidate to Technical Round 2 based on evaluator review.",
    ipAddress: "192.168.1.112",
    timestamp: "2026-10-02T11:15:00Z",
  },
  {
    id: "audit-3",
    actorName: "Dr. Rajesh K. Varma",
    actorRole: "PLACEMENT_ADMIN",
    action: "ELIGIBILITY_RULE_MODIFIED",
    targetType: "Drive",
    targetId: "drive-4",
    targetTitle: "Oracle Cloud Infrastructure",
    details: "Relaxed active backlogs threshold from 0 to 1 upon recruiter consultation.",
    ipAddress: "192.168.1.104",
    timestamp: "2026-10-01T10:15:00Z",
  },
  {
    id: "audit-4",
    actorName: "Vikram Malhotra",
    actorRole: "RECRUITER",
    action: "INTERVIEW_SCHEDULED",
    targetType: "Interview",
    targetId: "int-1",
    targetTitle: "Aarav Sharma - Technical Round 2",
    details: "Scheduled virtual interview session on Zoom for Oct 08, 02:30 PM.",
    ipAddress: "204.14.23.8",
    timestamp: "2026-10-02T11:30:00Z",
  },
];
